/* 教学演示：数值来自当前控件或明确标注的小型算例。真实照片独立注明来源。 */
(() => {
  'use strict';
  const rgb = v => `rgb(${v.map(x=>Math.round(x)).join(',')})`;
  const textColor = v => { const l=v.map(n=>{const x=n/255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;});return l[0]*.2126+l[1]*.7152+l[2]*.0722>.179?'#111':'#fff'; };
  const fmt = x => Number(x).toFixed(3);
  function chart(canvas, xs, ys, color='#207d80', marker=null) {
    const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,p=42;
    c.clearRect(0,0,w,h);c.fillStyle='#fff';c.fillRect(0,0,w,h);
    const xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(0,...ys),ymax=Math.max(1,...ys);
    const X=x=>p+(x-xmin)/(xmax-xmin||1)*(w-2*p),Y=y=>h-p-(y-ymin)/(ymax-ymin||1)*(h-2*p);
    c.strokeStyle='#c8d6dc';c.lineWidth=1;c.beginPath();c.moveTo(p,p);c.lineTo(p,h-p);c.lineTo(w-p,h-p);c.stroke();
    if(xmin<0&&xmax>0){c.beginPath();c.moveTo(X(0),p);c.lineTo(X(0),h-p);c.stroke();}if(ymin<0){c.beginPath();c.moveTo(p,Y(0));c.lineTo(w-p,Y(0));c.stroke();}
    c.fillStyle='#354851';c.font='13px sans-serif';c.fillText(fmt(xmin),p,h-14);c.fillText(fmt(xmax),w-p-38,h-14);c.fillText(fmt(ymax),3,p+5);c.fillText(fmt(ymin),3,h-p);
    c.strokeStyle=color;c.lineWidth=3;c.beginPath();xs.forEach((x,i)=>i?c.lineTo(X(x),Y(ys[i])):c.moveTo(X(x),Y(ys[i])));c.stroke();
    if(marker){c.fillStyle='#d2781c';c.beginPath();c.arc(X(marker[0]),Y(marker[1]),6,0,2*Math.PI);c.fill();}
  }
  function pixels(el,gray=false){
    const values=gray?[0,51,102,153,204,255]:[[255,0,0],[0,255,0],[0,0,255],[255,255,255],[80,80,80],[245,160,40]];
    const start=JSON.parse(JSON.stringify(values));let selected=0;
    let layers=null;
    if(!gray){layers=document.createElement('div');layers.className='rgb-layers';['R 红色分量','G 绿色分量','B 蓝色分量'].forEach(name=>{const group=document.createElement('div');const title=document.createElement('p');title.textContent=name;group.append(title);const cells=document.createElement('div');cells.className='layer-grid';for(let i=0;i<6;i++)cells.append(document.createElement('span'));group.append(cells);layers.append(group);});el.querySelector('.pixel-grid').after(layers);}
    const grid=el.querySelector('.pixel-grid'),out=el.querySelector('output'),inputs=[...el.querySelectorAll('input')];
    values.forEach((v,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',`${gray?'灰度':'RGB'} 像素 ${i+1}`);b.addEventListener('click',()=>{selected=i;sync();});grid.append(b);});
    function sync(){values.forEach((v,i)=>{const b=grid.children[i],display=gray?[v,v,v]:v;b.style.backgroundColor=rgb(display);b.style.color=textColor(display);b.style.textShadow='none';b.textContent=`(${Math.floor(i/3)},${i%3})`;b.setAttribute('aria-pressed',String(selected===i));if(layers)for(let c=0;c<3;c++){const cell=layers.children[c].querySelector('.layer-grid').children[i],color=[0,0,0];color[c]=v[c];cell.style.background=rgb(color);cell.style.color=textColor(color);cell.textContent=v[c];cell.classList.toggle('selected',i===selected);}});inputs.forEach((v,i)=>v.value=gray?values[selected]:values[selected][i]);out.textContent=gray?`行 ${Math.floor(selected/3)}，列 ${selected%3}：${values[selected]}。矩阵：[[${values.slice(0,3).join(', ')}], [${values.slice(3).join(', ')}]]`:`行 ${Math.floor(selected/3)}，列 ${selected%3}：RGB = (${values[selected].join(', ')})。三个通道的这个位置分别是 R=${values[selected][0]}，G=${values[selected][1]}，B=${values[selected][2]}。`;}
    inputs.forEach((input,i)=>input.addEventListener('input',()=>{const n=Math.max(0,Math.min(255,Number(input.value)||0));if(gray)values[selected]=n;else values[selected][i]=n;sync();}));
    el.querySelector('[data-reset]').addEventListener('click',()=>{start.forEach((v,i)=>values[i]=gray?v:[...v]);selected=0;sync();});sync();
  }
  function alpha(el){const controls=[...el.querySelectorAll('input')],patch=el.querySelector('.rgba-patch'),out=el.querySelector('output');function draw(){const [r,g,b,a]=controls.map(i=>+i.value);patch.style.backgroundColor=`rgba(${r},${g},${b},${a})`;patch.textContent=`Alpha ${a.toFixed(2)}`;out.textContent=`RGBA = (${r}, ${g}, ${b}, ${a.toFixed(2)})；背景白色时显示 RGB ≈ (${[r,g,b].map(v=>Math.round(a*v+(1-a)*255)).join(', ')})。Alpha 为 0 时保留颜色数值，但显示完全取决于背景。`;}controls.forEach(i=>i.addEventListener('input',draw));draw();}
  function bgr(el){const inputs=[...el.querySelectorAll('input')],patches=el.querySelectorAll('.rgba-patch');function draw(){const v=inputs.map(i=>+i.value);patches[0].style.background=rgb(v);patches[1].style.background=rgb([...v].reverse());el.querySelector('output').textContent=`原 RGB = (${v.join(', ')})；BGR 存储次序 = (${[...v].reverse().join(', ')})。右图把 BGR 数组直接当作 RGB 显示，红蓝交换；重新排列为 RGB 后恢复左图。`;}inputs.forEach(i=>i.addEventListener('input',draw));draw();}
  function transforms(el){const img=new Image(),cs=el.querySelectorAll('canvas'),controls=el.querySelectorAll('select,input');img.src=el.dataset.photo;function draw(){if(!img.complete||!img.naturalWidth)return;const op=controls[0].value,side=+controls[1].value,inter=controls[2].value;
      const src=cs[0].getContext('2d');src.drawImage(img,0,0,cs[0].width,cs[0].height);
      const tiny=document.createElement('canvas');tiny.width=side;tiny.height=side;const t=tiny.getContext('2d');t.imageSmoothingEnabled=inter!=='nearest';t.imageSmoothingQuality='high';
      if(op==='crop'){const s=Math.min(img.naturalWidth,img.naturalHeight)*.5;t.drawImage(img,(img.naturalWidth-s)/2,(img.naturalHeight-s)/2,s,s,0,0,side,side);}else t.drawImage(img,0,0,side,side);
      const dest=cs[1].getContext('2d');dest.imageSmoothingEnabled=op==='interpolate'&&inter!=='nearest';dest.drawImage(tiny,0,0,cs[1].width,cs[1].height);
      el.querySelector('output').textContent=op==='crop'?`中央裁剪保留原图中央一半边长的区域，再调整到 ${side}×${side}；图外部分已移除。`:`原始 ${img.naturalWidth}×${img.naturalHeight} → ${side}×${side}。${op==='interpolate'?'再放大到展示画布，对比最近邻的方块与平滑插值的过渡。':'输出用最近邻放大展示，方便观察保存了多少个像素。'} 插值：${inter==='nearest'?'最近邻':'浏览器 Canvas 平滑插值'}。`;}
    img.onload=draw;controls.forEach(i=>i.addEventListener('input',draw));}
  function activation(el){const fns={relu:x=>Math.max(0,x),sigmoid:x=>1/(1+Math.exp(-x)),tanh:Math.tanh};const sel=el.querySelector('select'),input=el.querySelector('input');function draw(){const f=fns[sel.value],x=+input.value,xs=Array.from({length:201},(_,i)=>-4+i*.04);chart(el.querySelector('canvas'),xs,xs.map(f),'#207d80',[x,f(x)]);el.querySelector('output').textContent=`输入 z=${x.toFixed(1)} → ${sel.options[sel.selectedIndex].text} → 输出 ${fmt(f(x))}。横轴是输入，纵轴是输出。${sel.value==='relu'?'负数变成 0，正数保留。':sel.value==='sigmoid'?'所有有限输入压入 0—1；接近两端时变化较慢。':'输出落在 −1—1，正负输入的符号保留。'}`;}[sel,input].forEach(i=>i.addEventListener('input',draw));draw();}
  function convolution(el){const input=el.querySelector('input');function draw(){const pos=+input.value,row=Math.floor(pos/3),col=pos%3,canvas=el.querySelector('canvas'),c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);let sum=0;for(let y=0;y<5;y++)for(let x=0;x<5;x++){const chosen=y>=row&&y<row+3&&x>=col&&x<col+3,n=y*5+x+1;if(chosen)sum+=n;c.fillStyle=chosen?'#d3ebdf':'#edf2f4';c.fillRect(34+x*49,18+y*49,47,47);c.fillStyle='#223841';c.font='18px sans-serif';c.fillText(n,46+x*49,48+y*49);}el.querySelector('output').textContent=`窗口左上角：（${row}, ${col}）。9 个输入分别乘以 1 后求和 = ${sum}。3×3 卷积核不填充、步长为 1 时，5×5 输入产生 3×3 输出；滑块遍历这 9 个位置。`;}input.addEventListener('input',draw);draw();}
  function overlap(el){const truth=[0,0,0,0,0,0,1,1,1,0,0,1,1,1,0,0,1,1,1,0,0,0,0,0,0],pred=[...truth];const grids=el.querySelectorAll('.metric-grid');truth.forEach((v,i)=>{for(let g=0;g<2;g++){const b=document.createElement('button');b.type='button';b.textContent=v;b.className=v?'on':'off';b.setAttribute('aria-label',`${g?'预测':'标注'}像素 ${i+1}`);if(g===0)b.disabled=true;else b.addEventListener('click',()=>{pred[i]=1-pred[i];update();});grids[g].append(b);}});function update(){let inter=0,p=0,t=0;truth.forEach((v,i)=>{t+=v;p+=pred[i];inter+=v&&pred[i];const b=grids[1].children[i];b.className=pred[i]?'on':'off';b.textContent=pred[i];b.setAttribute('aria-pressed',String(!!pred[i]));});const union=t+p-inter;el.querySelector('output').textContent=`标注前景 ${t}，预测前景 ${p}，交集 ${inter}，并集 ${union}；Dice = 2×${inter}÷(${t}+${p}) = ${fmt(2*inter/(t+p))}；IoU = ${inter}÷${union} = ${fmt(inter/union)}。`;}el.querySelector('[data-reset]').addEventListener('click',()=>{truth.forEach((v,i)=>pred[i]=v);update();});update();}
  function threshold(el){const scores=[.08,.12,.2,.15,.03,.14,.4,.65,.42,.13,.2,.7,.92,.68,.15,.1,.45,.7,.48,.08,.03,.1,.2,.09,.01],grid=el.querySelector('.metric-grid'),input=el.querySelector('input');scores.forEach((s,i)=>{const b=document.createElement('button');b.disabled=true;b.textContent=s.toFixed(2);b.setAttribute('aria-label',`像素 ${i+1}，分数 ${s}`);grid.append(b);});function draw(){let n=0; scores.forEach((s,i)=>{const on=s>=+input.value;n+=on;grid.children[i].className=on?'on':'off';});el.querySelector('output').textContent=`阈值 ${(+input.value).toFixed(2)}：分数达到阈值的 ${n} 个位置变成前景。分数来自教学算例，改变阈值会改变预测区域，不改变标注。`;}input.addEventListener('input',draw);draw();}
  function loss(el){const input=el.querySelector('input'),reference=[.8,.4,.2];function draw(){const amount=+input.value,pred=reference.map(v=>Math.min(1,Math.max(0,v+amount))),errors=pred.map((v,i)=>Math.abs(v-reference[i]));const boxes=el.querySelectorAll('.rgba-patch');boxes[0].style.background=rgb(reference.map(x=>x*255));boxes[1].style.background=rgb(pred.map(x=>x*255));el.querySelector('output').textContent=`参考 RGB = (${reference.join(', ')})；预测 RGB = (${pred.map(fmt).join(', ')})；各通道绝对误差 = (${errors.map(fmt).join(', ')})；这个像素的 MAE = ${fmt(errors.reduce((a,b)=>a+b,0)/3)}。达到 0 或 1 后会截断，误差不再随滑块完全线性变化。`;}input.addEventListener('input',draw);draw();}
  document.querySelectorAll('.visual-lab').forEach(el=>{try{const type=el.dataset.lab;if(type==='rgb')pixels(el);else if(type==='gray')pixels(el,true);else ({alpha,bgr,transforms,activation,convolution,overlap,threshold,loss}[type]||(()=>{}))(el);}catch(e){el.querySelector('output').textContent='演示未能加载，请刷新页面。';console.error(e);}});
})();
